version: '3.9'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=codo_maton
    volumes:
      - codo_maton-db-data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - database
    restart: always
    ports:
      - 7878:7878
    volumes:
      - temp:/temp
      - videos:/videos

volumes:
  codo_maton-db-data:
  temp:
    external: true
  videos:
    external: true

networks:
  default:
    external:
      name: projet-dev-network
